insert into SM_APPPAGE ( PAGEURL,PARENT_ID,PARENTCODE,RESID,ISDEFAULT,ISCARDDEFAULT,CREATOR,CREATIONTIME,MODIFIER,MODIFIEDTIME,PAGEJSURL,PAGERESFILE,STYLETYPE,MOBPAGERESFILE,ISNEWPAGE,TRANSFERSIGN,PK_APPPAGE,PAGECODE,PAGENAME,PAGEDESC,DR,TS ) values  ( '/nccloud/resources/vehicle/vorder/vorderhvop/main/index.html','1001AA1LCP00000IVA08','40VE01P',null,'Y','Y',null,null,null,null,null,null,null,null,null,null,'1001AA1LCP00000IVDPD','40VE01P_VorderHVOP','用车申请单审批',null,0,'2023-04-28 14:27:45' ) 
/

