insert into SM_APPPAGE ( PAGEURL,PARENT_ID,PARENTCODE,RESID,ISDEFAULT,ISCARDDEFAULT,CREATOR,CREATIONTIME,MODIFIER,MODIFIEDTIME,PAGEJSURL,PAGERESFILE,STYLETYPE,MOBPAGERESFILE,ISNEWPAGE,TRANSFERSIGN,PK_APPPAGE,PAGECODE,PAGENAME,PAGEDESC,DR,TS ) values  ( '/nccloud/resources/vehicle/vorder/vorderhvol/main/index.html','1001AA1LCP00000IVA52','40VE01L',null,'Y','Y',null,null,null,null,null,null,null,null,null,null,'1001AA1LCP00000IVDU5','40VE01L_VorderHVOL','用车申请单联查',null,0,'2023-04-28 14:27:45' ) 
/

