insert into PUB_BCR_RULEBASE ( CODEMODE,CODESCOPE,FORMAT,ISAUTOFILL,ISDEFAULT,ISEDITABLE,NBCRCODE,PK_BILLCODEBASE,PK_GROUP,RULECODE,RULENAME,ISLENVAR,ISGETPK,DR,TS ) values  ( 'after','g','yyyyMMdd','N','Y','N','uapbdPriceManage','1001AA1LCP0000002GUM','GLOBLE00000000000000','uapbdPriceManage','客户价格管理','Y','N',null,null ) 
/

