insert into SM_APPPAGE ( PK_APPPAGE,PAGECODE,PAGENAME,PAGEDESC,PAGEURL,PARENT_ID,PARENTCODE,RESID,ISDEFAULT,ISCARDDEFAULT,CREATOR,CREATIONTIME,MODIFIER,MODIFIEDTIME,PAGEJSURL,PAGERESFILE,STYLETYPE,MOBPAGERESFILE,ISNEWPAGE,TRANSFERSIGN,DR,TS ) values  ( '1001AA1LCP00000029GQ','DDH20101L_RefreshCostHVOL','成本对象主表联查',null,'/nccloud/resources/dd/refreshcost/refreshcosthvol/main/index.html','1001AA1LCP0000000ZAJ','DDH20101L',null,'Y','Y',null,null,null,null,null,null,null,null,null,null,0,'2023-04-03 09:44:47' ) 
/

