insert into PUB_BCR_RULEBASE ( CODEMODE,CODESCOPE,FORMAT,ISAUTOFILL,ISDEFAULT,ISEDITABLE,NBCRCODE,PK_BILLCODEBASE,PK_GROUP,RULECODE,RULENAME,ISLENVAR,ISGETPK,DR,TS ) values  ( 'after','g','yyyyMMdd','N','Y','N','vehiclevorder','1001AA1LCP00000IVDOU','GLOBLE00000000000000','vehiclevorder','用车申请单','Y','N',null,null ) 
/

