insert into BD_REFINFO ( CODE,ISTREELAZYLOAD,ISNEEDPARA,ISSPECIALREF,LAYER,REFTYPE,METADATANAMESPACE,METADATATYPENAME,MOBILEREFPATH,MODULENAME,NAME,PARA1,PARA2,PARA3,PK_COUNTRY,PK_INDUSTRY,PK_REFINFO,REFCLASS,REFPATH,REFSYSTEM,RESERV1,RESERV2,RESERV3,RESID,RESIDPATH,WHEREPART,WORKFLOWCONDITIONUSEUNITORG,TS,DR ) values  ( '40H40101','N',null,null,null,0,'hanwang','xfmx',null,'stgl','xfmx_消费明细_默认表参照_xfmx_xfmx',null,null,null,null,null,'1001AA1LCP0000003082',null,'stgl/refer/xfmx/xfmxDefaultGridRef/index',null,null,null,null,'xfmx','xfmx',null,null,'2023-04-04 12:56:07',0 ) 
/

