insert into PUB_BILLACTION ( PK_BILLACTION,PK_BILLTYPE,PK_BILLTYPEID,ACTION_TYPE,ACTIONNOTE,ACTIONNOTE2,ACTIONNOTE3,ACTIONNOTE4,ACTIONNOTE5,ACTIONNOTE6,ACTIONSTYLE,ACTIONSTYLEREMARK,ACTIONTYPE,CONSTRICTFLAG,CONTROLFLAG,FINISHFLAG,PUSHFLAG,SHOWHINT,SHOWHINT2,SHOWHINT3,SHOWHINT4,SHOWHINT5,SHOWHINT6,DR,TS ) values  ( '1001AA1LCP00000IVDOY','40VE01','40VE01',31,'保存',null,null,null,null,null,'0',null,'SAVEBASE','N','Y','Y',null,null,null,null,null,null,null,0,'2023-04-28 14:27:45' ) 
/

insert into PUB_BILLACTION ( PK_BILLACTION,PK_BILLTYPE,PK_BILLTYPEID,ACTION_TYPE,ACTIONNOTE,ACTIONNOTE2,ACTIONNOTE3,ACTIONNOTE4,ACTIONNOTE5,ACTIONNOTE6,ACTIONSTYLE,ACTIONSTYLEREMARK,ACTIONTYPE,CONSTRICTFLAG,CONTROLFLAG,FINISHFLAG,PUSHFLAG,SHOWHINT,SHOWHINT2,SHOWHINT3,SHOWHINT4,SHOWHINT5,SHOWHINT6,DR,TS ) values  ( '1001AA1LCP00000IVDOZ','40VE01','40VE01',10,'提交',null,null,null,null,null,'3',null,'SAVE','N','Y','Y',null,null,null,null,null,null,null,0,'2023-04-28 14:27:45' ) 
/

insert into PUB_BILLACTION ( PK_BILLACTION,PK_BILLTYPE,PK_BILLTYPEID,ACTION_TYPE,ACTIONNOTE,ACTIONNOTE2,ACTIONNOTE3,ACTIONNOTE4,ACTIONNOTE5,ACTIONNOTE6,ACTIONSTYLE,ACTIONSTYLEREMARK,ACTIONTYPE,CONSTRICTFLAG,CONTROLFLAG,FINISHFLAG,PUSHFLAG,SHOWHINT,SHOWHINT2,SHOWHINT3,SHOWHINT4,SHOWHINT5,SHOWHINT6,DR,TS ) values  ( '1001AA1LCP00000IVDP0','40VE01','40VE01',13,'收回',null,null,null,null,null,'3',null,'UNSAVE','N','Y','Y',null,null,null,null,null,null,null,0,'2023-04-28 14:27:45' ) 
/

insert into PUB_BILLACTION ( PK_BILLACTION,PK_BILLTYPE,PK_BILLTYPEID,ACTION_TYPE,ACTIONNOTE,ACTIONNOTE2,ACTIONNOTE3,ACTIONNOTE4,ACTIONNOTE5,ACTIONNOTE6,ACTIONSTYLE,ACTIONSTYLEREMARK,ACTIONTYPE,CONSTRICTFLAG,CONTROLFLAG,FINISHFLAG,PUSHFLAG,SHOWHINT,SHOWHINT2,SHOWHINT3,SHOWHINT4,SHOWHINT5,SHOWHINT6,DR,TS ) values  ( '1001AA1LCP00000IVDP1','40VE01','40VE01',11,'审批',null,null,null,null,null,'2',null,'APPROVE','N','Y','Y',null,null,null,null,null,null,null,0,'2023-04-28 14:27:45' ) 
/

insert into PUB_BILLACTION ( PK_BILLACTION,PK_BILLTYPE,PK_BILLTYPEID,ACTION_TYPE,ACTIONNOTE,ACTIONNOTE2,ACTIONNOTE3,ACTIONNOTE4,ACTIONNOTE5,ACTIONNOTE6,ACTIONSTYLE,ACTIONSTYLEREMARK,ACTIONTYPE,CONSTRICTFLAG,CONTROLFLAG,FINISHFLAG,PUSHFLAG,SHOWHINT,SHOWHINT2,SHOWHINT3,SHOWHINT4,SHOWHINT5,SHOWHINT6,DR,TS ) values  ( '1001AA1LCP00000IVDP2','40VE01','40VE01',12,'取消审批',null,null,null,null,null,'3',null,'UNAPPROVE','N','Y','Y',null,null,null,null,null,null,null,0,'2023-04-28 14:27:45' ) 
/

