insert into SM_APPPAGE ( PAGEURL,PARENT_ID,PARENTCODE,RESID,ISDEFAULT,ISCARDDEFAULT,CREATOR,CREATIONTIME,MODIFIER,MODIFIEDTIME,PAGEJSURL,PAGERESFILE,STYLETYPE,MOBPAGERESFILE,ISNEWPAGE,TRANSFERSIGN,PK_APPPAGE,PAGECODE,PAGENAME,PAGEDESC,DR,TS ) values  ( '/nccloud/resources/vehicle/vorder/vorderhvo/main/index.html','1001AA100000000IV9PS','40VE01',null,'Y',null,null,null,null,null,null,null,null,null,null,null,'1001AA1LCP00000IVABW','40VE01_VorderHVO','用车申请单',null,0,'2023-04-28 14:27:43' ) 
/

