insert into PUB_BCR_RULEBASE ( CODEMODE,CODESCOPE,FORMAT,ISAUTOFILL,ISDEFAULT,ISEDITABLE,NBCRCODE,PK_BILLCODEBASE,PK_GROUP,RULECODE,RULENAME,ISLENVAR,ISGETPK,DR,TS ) values  ( 'after','g','yyyyMMdd','N','Y','N','hanwangxfmx','1001AA1LCP000000307K','GLOBLE00000000000000','hanwangxfmx','消费明细','Y','N',null,null ) 
/

