 create table DD_REFRESHCOST (vdef10 varchar2(101) null /*自定义项10*/,
vdef9 varchar2(101) null /*自定义项9*/,
vdef8 varchar2(101) null /*自定义项8*/,
vdef7 varchar2(101) null /*自定义项7*/,
vdef6 varchar2(101) null /*自定义项6*/,
vdef5 varchar2(101) null /*自定义项5*/,
vdef4 varchar2(101) null /*自定义项4*/,
vdef3 varchar2(101) null /*自定义项3*/,
vdef2 varchar2(101) null /*自定义项2*/,
vdef1 varchar2(101) null /*自定义项1*/,
srcbillid varchar2(50) null /*来源单据id*/,
srcbilltype varchar2(20) null /*来源单据类型*/,
billversionpk varchar2(50) null /*单据版本pk*/,
emendenum integer null /*修订枚举*/,
transtypepk varchar2(20) null /*交易类型pk*/,
billtype varchar2(20) null /*单据类型*/,
transtype varchar2(50) null /*交易类型*/,
approvedate char(19) null /*审批时间*/,
approvenote varchar2(50) null /*审批批语*/,
approvestatus integer null /*审批状态*/,
approver varchar2(20) null /*审批人*/,
modifiedtime char(19) null /*修改时间*/,
modifier varchar2(20) null /*修改人*/,
maketime char(19) null /*制单时间*/,
billmaker varchar2(20) null /*制单人*/,
busitype varchar2(20) null /*业务类型*/,
pkorg varchar2(20) null /*所属组织*/,
vmemo varchar2(50) null /*备注*/,
billcode varchar2(50) null /*单据号*/,
pk_period varchar2(20) null /*会计期间*/,
dbilldate char(19) null /*单据日期*/,
creationtime char(19) null /*创建时间*/,
creator varchar2(20) null /*创建人*/,
pk_org_v varchar2(20) null /*组织版本*/,
pk_org varchar2(20) null /*组织*/,
pk_group varchar2(20) null /*集团*/,
name varchar2(50) null /*名称*/,
code varchar2(50) null /*编码*/,
pk_cost char(20) not null /*主键*/,
ts char(19) default to_char(sysdate,'yyyy-mm-dd hh24:mi:ss') null /*null*/,
dr integer null /*null*/,
 constraint DD_REFRESHCOST_PK  primary key (pk_cost)
)

/

 create table DD_REFRESHCOST_B (vbdef10 varchar2(101) null /*自定义项10*/,
vbdef9 varchar2(101) null /*自定义项9*/,
vbdef8 varchar2(101) null /*自定义项8*/,
vbdef7 varchar2(101) null /*自定义项7*/,
vbdef6 varchar2(101) null /*自定义项6*/,
vbdef5 varchar2(101) null /*自定义项5*/,
vbdef4 varchar2(101) null /*自定义项4*/,
vbdef3 varchar2(101) null /*自定义项3*/,
vbdef2 varchar2(101) null /*自定义项2*/,
vbdef1 varchar2(101) null /*自定义项1*/,
srcbillid varchar2(50) null /*来源单据id*/,
srcbilltype varchar2(50) null /*来源单据类型*/,
vbmemo varchar2(101) null /*备注*/,
srcrowno varchar2(50) null /*来源行号*/,
is_other char(1) null /*其它已发生*/,
is_energy char(1) null /*能源已发生*/,
is_spare char(1) null /*配件已发生*/,
pk_user varchar2(20) null /*责任人*/,
pk_usedept varchar2(20) null /*使用部门*/,
pk_manager varchar2(20) null /*管理人*/,
pk_mandept varchar2(20) null /*管理部门*/,
pk_location varchar2(20) null /*位置*/,
pk_capital_source varchar2(20) null /*资金来源*/,
pk_priority varchar2(20) null /*关键程度*/,
status_date char(19) null /*状态日期*/,
pk_used_status varchar2(20) null /*设备状态*/,
pk_category varchar2(20) null /*设备类别*/,
equiptype varchar2(80) null /*型号*/,
spec varchar2(80) null /*规格*/,
pk_group varchar2(20) null /*集团*/,
pk_org_v varchar2(20) null /*资产组织版本*/,
pk_org varchar2(20) null /*资产组织*/,
equip_name3 varchar2(50) null /*子子设备名称*/,
equip_code3 varchar2(50) null /*子子设备编码*/,
equip_name2 varchar2(50) null /*子设备名称*/,
equip_code2 varchar2(50) null /*子设备编码*/,
equip_name varchar2(50) null /*设备名称*/,
equip_code varchar2(50) null /*设备编码*/,
rowno varchar2(50) null /*行号*/,
pk_cost_b char(20) not null /*主键*/,
pk_cost char(20) not null /*上层单据主键*/,
ts char(19) default to_char(sysdate,'yyyy-mm-dd hh24:mi:ss') null /*null*/,
dr integer null /*null*/,
 constraint DD_REFRESHCOST_B_PK  primary key (pk_cost_b)
)

/

