 create table CL_VORDER (pk_driver varchar2(20) null /*司机主键*/,
travelmileage number(28,8) null /*行驶里程*/,
backmileage number(28,8) null /*返回里程*/,
startmileage number(28,8) null /*出发里程*/,
billversionpk varchar2(50) null /*单据版本pk*/,
emendenum integer null /*修订枚举*/,
srcbillid varchar2(50) null /*来源单据id*/,
srcbilltype varchar2(20) null /*来源单据类型*/,
transtypepk varchar2(20) null /*交易类型pk*/,
billtype varchar2(50) null /*单据类型*/,
transtype varchar2(50) null /*交易类型*/,
approvedate char(19) null /*审批时间*/,
approvenote varchar2(50) null /*审批批语*/,
approvestatus integer null /*审批状态*/,
approver varchar2(20) null /*审批人*/,
billmaker varchar2(20) null /*制单人*/,
busitype varchar2(20) null /*业务类型*/,
modifiedtime char(19) null /*修改时间*/,
modifier varchar2(20) null /*修改人*/,
creationtime char(19) null /*创建时间*/,
creator varchar2(20) null /*创建人*/,
vbilldate char(19) null /*单据日期*/,
lastmaketime char(19) null /*最后修改时间*/,
maketime char(19) null /*制单时间*/,
name varchar2(50) null /*name*/,
code varchar2(50) null /*code*/,
pk_org_v varchar2(20) null /*组织版本*/,
pk_org varchar2(20) null /*组织*/,
pk_group varchar2(20) null /*集团*/,
def10 varchar2(101) null /*自定义项10*/,
def9 varchar2(101) null /*自定义项8*/,
def8 varchar2(101) null /*自定义项7*/,
def7 varchar2(101) null /*自定义项6*/,
def6 varchar2(101) null /*自定义项5*/,
def5 varchar2(101) null /*自定义项4*/,
def4 varchar2(101) null /*自定义项3*/,
def3 varchar2(101) null /*自定义项2*/,
def2 varchar2(101) null /*自定义项1*/,
def1 varchar2(101) null /*自定义项0*/,
endtime char(19) null /*结束时间*/,
begintime char(19) null /*开始时间*/,
remainpnum integer null /*剩余人数*/,
destarea varchar2(50) null /*目标区域*/,
fdestination varchar2(50) null /*最终目的地*/,
origin varchar2(50) null /*出发地*/,
billstate varchar2(50) null /*单据状态*/,
pk_vehicle varchar2(20) null /*车辆主键*/,
vehicleno varchar2(50) null /*车牌号*/,
dphone varchar2(50) null /*司机电话*/,
driver varchar2(50) null /*司机*/,
iscarpool char(1) null /*是否可拼车*/,
billno varchar2(50) null /*订单号*/,
pk_vorder char(20) not null /*主键*/,
ts char(19) default to_char(sysdate,'yyyy-mm-dd hh24:mi:ss') null /*null*/,
dr integer null /*null*/,
 constraint CL_VORDER_PK  primary key (pk_vorder)
)

/

 create table CL_VORDER_B (review varchar2(500) null /*评价*/,
starlevel integer null /*星级*/,
pk_org_v varchar2(20) null /*组织版本*/,
pk_org varchar2(20) null /*组织*/,
pk_group varchar2(20) null /*集团*/,
rowno varchar2(50) null /*行号*/,
name varchar2(50) null /*name*/,
code varchar2(50) null /*code*/,
id char(20) null /*id*/,
def10 varchar2(101) null /*自定义项10*/,
def9 varchar2(101) null /*自定义项8*/,
def8 varchar2(101) null /*自定义项7*/,
def7 varchar2(101) null /*自定义项6*/,
def6 varchar2(101) null /*自定义项5*/,
def5 varchar2(101) null /*自定义项4*/,
def4 varchar2(101) null /*自定义项3*/,
def3 varchar2(101) null /*自定义项2*/,
def2 varchar2(101) null /*自定义项1*/,
def1 varchar2(101) null /*自定义项0*/,
selectpnum integer null /*人数*/,
cancelreason varchar2(50) null /*取消原因*/,
turndownreason varchar2(50) null /*驳回原因*/,
remark varchar2(50) null /*事由*/,
returntime char(19) null /*返回时间*/,
departtime char(19) null /*出发时间*/,
destarea varchar2(50) null /*目标区域*/,
finaldest varchar2(50) null /*最终目的地*/,
dest5 varchar2(50) null /*目的地五*/,
dest4 varchar2(50) null /*目的地四*/,
dest3 varchar2(50) null /*目的地三*/,
dest2 varchar2(50) null /*目的地二*/,
dest1 varchar2(50) null /*目的地一*/,
origin varchar2(50) null /*出发地*/,
phone varchar2(50) null /*联系电话*/,
dept varchar2(20) null /*申请部门*/,
applier varchar2(20) null /*拼车人*/,
isfisrtapplier char(1) null /*第一申请人*/,
pk_vorder_b char(20) not null /*主键*/,
ts char(19) default to_char(sysdate,'yyyy-mm-dd hh24:mi:ss') null /*null*/,
dr integer null /*null*/,
pk_vorder char(20) not null /*上层单据主键*/,
 constraint CL_VORDER_B_PK  primary key (pk_vorder_b)
)

/

