 create table COMSUMELOG (vdef20 varchar2(101) null /*自定义项20*/,
vdef19 varchar2(101) null /*自定义项19*/,
vdef18 varchar2(101) null /*自定义项18*/,
vdef17 varchar2(101) null /*自定义项17*/,
vdef16 varchar2(101) null /*自定义项16*/,
vdef15 varchar2(101) null /*自定义项15*/,
vdef14 varchar2(101) null /*自定义项14*/,
vdef13 varchar2(101) null /*自定义项13*/,
vdef12 varchar2(101) null /*自定义项12*/,
vdef11 varchar2(101) null /*自定义项11*/,
vdef10 varchar2(101) null /*自定义项10*/,
vdef9 varchar2(101) null /*自定义项9*/,
vdef8 varchar2(101) null /*自定义项8*/,
vdef7 varchar2(101) null /*自定义项7*/,
vdef6 varchar2(101) null /*自定义项6*/,
vdef5 varchar2(101) null /*自定义项5*/,
vdef4 varchar2(101) null /*自定义项4*/,
vdef3 varchar2(101) null /*自定义项3*/,
vdef2 varchar2(101) null /*自定义项2*/,
vdef1 varchar2(101) null /*自定义项1*/,
tnumber number(28,8) null /*次数*/,
note varchar2(200) null /*备注*/,
ymoney number(28,8) null /*余额*/,
xfmoney number(28,8) null /*消费金额*/,
xftype varchar2(50) null /*消费类型*/,
xfdate char(8) null /*消费时间*/,
operation varchar2(50) null /*操作*/,
psndocname varchar2(20) default '~' null /*员工姓名*/,
psndoccode varchar2(50) null /*员工编码*/,
deptname varchar2(20) default '~' null /*部门名称*/,
deptcode varchar2(50) null /*部门编码*/,
approvestatus integer null /*审批状态*/,
emendenum integer null /*修订枚举*/,
billversionpk varchar2(50) null /*单据版本pk*/,
srcbillid char(20) null /*来源单据id*/,
srcbilltype varchar2(20) default '~' null /*来源单据类型*/,
transtypepk varchar2(20) default '~' null /*交易类型pk*/,
transtype varchar2(50) null /*交易类型*/,
busitype varchar2(20) default '~' null /*业务类型*/,
billtype varchar2(20) default '~' null /*单据类型*/,
approvenote varchar2(50) null /*审批批语*/,
documentdate char(19) null /*制单日期*/,
billmaker varchar2(20) default '~' null /*制单人*/,
billno varchar2(50) null /*单据号*/,
approvedate char(19) null /*审批时间*/,
approver varchar2(20) default '~' null /*审批人*/,
billdate char(19) null /*单据日期*/,
modifiedtime char(19) null /*修改时间*/,
modifier varchar2(20) default '~' null /*修改人*/,
creationtime char(19) null /*创建时间*/,
creator varchar2(20) default '~' null /*创建人*/,
pk_org_v varchar2(20) default '~' null /*组织版本*/,
pk_org varchar2(20) default '~' null /*组织*/,
pk_group varchar2(20) default '~' null /*集团*/,
name varchar2(50) null /*名称*/,
code varchar2(50) null /*编码*/,
pk_xfmx char(20) not null /*消费明细主键*/,
ts char(19) default to_char(sysdate,'yyyy-mm-dd hh24:mi:ss') null /*null*/,
dr integer null /*null*/,
 constraint COMSUMELOG_PK  primary key (pk_xfmx)
)

/

